apiVersion: v1
kind: Service
metadata:
  labels:
    app: currencyconvertor
    environment: Development
  name: currencyconvertor
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: currencyconvertor
  sessionAffinity: None
  type: ClusterIP
